// include/version.h
// (Autogenerated from cmake/version.h.in)
#pragma once

#define PROJECT_NAME "cpp_project_template"

// Numeric components — usable in preprocessor #if comparisons, e.g.
//   #if PROJECT_VERSION_MAJOR >= 2 || (PROJECT_VERSION_MAJOR == 1 && PROJECT_VERSION_MINOR >= 5)
#define PROJECT_VERSION_MAJOR 1
#define PROJECT_VERSION_MINOR 0
#define PROJECT_VERSION_PATCH 0

// Human-readable string, e.g. for logging / --version output.
#define PROJECT_VERSION_STRING "1.0.0"
