# conan-profiles/clang-cl-windows-release.ini
[settings]
arch=x86_64
os=Windows
build_type=Release
compiler=msvc
compiler.version=194
compiler.cppstd=23
compiler.runtime=dynamic
compiler.runtime_type=Release

[conf]
tools.build:compiler_executables={"c":"clang-cl","cpp":"clang-cl","rc":"llvm-rc"}
