#pragma once
#include "MyLib/mylib_export.h" // MYLIB_EXPORT — generated by generate_export_header() at configure time

namespace mymath {

MYLIB_EXPORT auto add(int a, int b) -> int;
MYLIB_EXPORT auto subtract(int a, int b) -> int;
MYLIB_EXPORT auto multiply(int a, int b) -> int;
MYLIB_EXPORT auto divide(double a, double b) -> double;

}; // namespace mymath
